---
name: publish
on:
  push:
    tags:
      - '*'
jobs:
  create-release:
    name: create release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      -
        name: create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: true
          generate_release_notes: false
  artifact-build:
    name: artifact build
    needs: create-release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        arch:
          - amd64
          - arm64
        include:
          -
            os: macos-latest
            goos: darwin
            extldflags: -L${{ github.workspace }}/target/release -lvdf -lbls48581 -ldl -lm
            rustflags: -L /opt/homebrew/Cellar/gmp/6.3.0/lib
          -
            os: ubuntu-latest
            goos: linux
            extldflags: -L${GITHUB_WORKSPACE}/target/release -Wl,-Bstatic -lvdf -lbls48581 -Wl,-Bdynamic -ldl -lm
            rustflags: -L /usr/lib/x86_64-linux-gnu
        exclude:
          -
            os: macos-latest
            arch: amd64
    runs-on: ${{ matrix.os }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      -
        name: source fetch
        uses: actions/checkout@v4
      -
        name: read version
        run: |
          echo "GIT_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "SHORT_GIT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "QUILIBRIUM_VERSION=$(cat ${GITHUB_WORKSPACE}/node/config/version.go | grep -A 1 'func GetVersion() \[\]byte {' | grep -Eo '0x[0-9a-fA-F]+' | xargs printf '%d.%d.%d')" >> $GITHUB_ENV
      -
        name: verify tag and version match
        run: |
          if [ "${GIT_TAG}" = "v${QUILIBRIUM_VERSION}-${SHORT_GIT_SHA}" ]; then
            echo "git tag: ${GIT_TAG}"
            echo "short git sha: ${SHORT_GIT_SHA}"
            echo "quilibrium version: ${QUILIBRIUM_VERSION}"
          else
            echo "version in node/config/version.go (${QUILIBRIUM_VERSION}) does not match tag (${GIT_TAG})"
            echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
            exit 1
          fi
      -
        name: go setup
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      -
        name: dependency setup
        run: |
          go install github.com/fullstorydev/grpcurl/cmd/grpcurl@v1.9.1
          cargo install \
            uniffi-bindgen-go \
            --git https://github.com/NordSecurity/uniffi-bindgen-go \
            --tag v0.2.1+v0.25.0
      -
        name: rust builds
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
        run: |
          cargo build --package bls48581 --release
          cargo build --package vdf --release
      -
        name: bls48581 go bindings generation
        run: |
          pushd ${GITHUB_WORKSPACE}/crates/bls48581
          uniffi-bindgen-go ${GITHUB_WORKSPACE}/crates/bls48581/src/lib.udl -o ${GITHUB_WORKSPACE}/bls48581/generated
      -
        name: vdf go bindings generation
        run: |
          pushd ${GITHUB_WORKSPACE}/crates/vdf
          uniffi-bindgen-go ${GITHUB_WORKSPACE}/crates/vdf/src/lib.udl -o ${GITHUB_WORKSPACE}/vdf/generated
      -
        name: node build
        env:
          CGO_ENABLED: 1
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.goos }}
        run: |
          pushd ${GITHUB_WORKSPACE}/node
          go build -ldflags "-linkmode 'external' -extldflags '${{ matrix.extldflags }}'" -o ${GITHUB_WORKSPACE}/quilibrium-${GIT_TAG}-${{ matrix.goos }}-${{ matrix.arch }}
      -
        name: create digests
        run: |
          pushd ${GITHUB_WORKSPACE}
          ls -ahl ${GITHUB_WORKSPACE}
          openssl sha3-256 -out ${GITHUB_WORKSPACE}/quilibrium-${GIT_TAG}-${{ matrix.goos }}.dgst ${GITHUB_WORKSPACE}/quilibrium-${GIT_TAG}-${{ matrix.goos }}-${{ matrix.arch }}
          ls -ahl ${GITHUB_WORKSPACE}
      -
        name: publish
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: |
            ${{ github.workspace }}/quilibrium-${GIT_TAG}-${{ matrix.goos }}-${{ matrix.arch }}
            ${{ github.workspace }}/quilibrium-${GIT_TAG}-${{ matrix.goos }}-${{ matrix.arch }}.dgst
